---      

- name: |
    SECTION1 | 1.1.2.1   | Configure /tmp
    SECTION1 | 1.1.2.1.1 | Ensure /tmp is a separate partition
    SECTION1 | 1.1.2.1.2 | Ensure nodev option set on /tmp partition
    SECTION1 | 1.1.2.1.3 | Ensure nosuid option set on /tmp partition
    SECTION1 | 1.1.2.1.4 | Ensure noexec option set on /tmp partition
  ansible.builtin.template:
    src: system/tmp.mount.j2
    dest: /etc/systemd/system/tmp.mount
    owner: "{{ cis_ubuntu2204_section1_owner_default }}"
    group: "{{ cis_ubuntu2204_section1_group_default }}"
    mode: "{{ cis_ubuntu2204_section1_mode_default }}"
#  notify:
#    - systemd restart and enable tmp.mount
#  when:
#    - cis_ubuntu2204_rule_1_1_2_1
  tags:
    - rule_1_1_2_1
    - server_l1
    - workstation_l1
