---

- name: "SECTION1 | 1.4.1 | Ensure bootloader password is set"
  when:
    - cis_ubuntu2204_set_boot_pass
    - cis_ubuntu2204_rule_1_4_1
  tags:
    - rule_1_4
    - server_l1
    - workstation_l1
    - molecule-idempotence-notest
  block:
    - name: "SECTION1 | 1.4.1 | Ensure bootloader password is set | generate password"
      ansible.builtin.shell: |
        set -o pipefail &&
          if [ '{{ cis_ubuntu2204_bootloader_password }}' == 'random' ]; then
            PASSWORD=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c12)
          else
            PASSWORD='{{ cis_ubuntu2204_bootloader_password }}'
          fi
        echo -e "$PASSWORD\n$PASSWORD" | grub-mkpasswd-pbkdf2 --iteration-count=600000 --salt=64 | awk '/grub.pbkdf/{print$NF}'
      register: cis_grub_bootloader_password
      args:
        executable: "{{ cis_ubuntu2204_shell_executable }}"
      changed_when: false
    - name: "SECTION1 | 1.4.1 | Ensure bootloader password is set | generate config"
      ansible.builtin.copy:
        dest: /etc/grub.d/00_password
        content: "cat << EOF\nexec tail -n +2 $0\nset superusers=\"root\"\npassword_pbkdf2 root {{ cis_grub_bootloader_password.stdout }}\nEOF"
        owner: "{{ cis_ubuntu2204_section1_owner_default }}"
        group: "{{ cis_ubuntu2204_section1_group_default }}"
        mode: "{{ cis_ubuntu2204_section1_mode_etc_grub_d }}"
      notify: generate new grub config
      when:
        - cis_grub_bootloader_password is defined
        - cis_grub_bootloader_password.stdout is defined
        - cis_grub_bootloader_password.stdout | length > 0
    - name: "SECTION1 | 1.4.1 | Ensure bootloader password is set | disable password for system boot"
      ansible.builtin.replace:
        path: /etc/grub.d/10_linux
        regexp: '--class os"'
        replace: '--class os --unrestricted"'
      notify: generate new grub config
      when:
        - cis_ubuntu2204_disable_boot_pass

