---

- name: "5.2.4 | PATCH | Ensure SSH access is limited"
  block:
      - name: "5.2.4 | PATCH | Ensure SSH access is limited | Add allowed users"
        ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^AllowUsers|^#AllowUsers'
            line: 'AllowUsers {{ ubtu24cis_sshd.allow_users }}'
            validate: 'sshd -t -f %s'
        notify: Restart sshd
        when: "ubtu24cis_sshd['allow_users']| default('') | length > 0 "

      - name: "5.2.4 | PATCH | Ensure SSH access is limited | Add allowed groups"
        ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^AllowGroups|^#AllowGroups'
            line: 'AllowGroups {{ ubtu24cis_sshd.allow_groups }}'
            validate: 'sshd -t -f %s'
        notify: Restart sshd
        when: "ubtu24cis_sshd['allow_groups']| default('') | length > 0"

      - name: "5.2.4 | PATCH | Ensure SSH access is limited | Add deny users"
        ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^DenyUsers|^#DenyUsers'
            line: 'DenyUsers {{ ubtu24cis_sshd.deny_users }} '
            validate: 'sshd -t -f %s'
        notify: Restart sshd
        when: "ubtu24cis_sshd['deny_users']| default('') | length > 0"

      - name: "5.2.4 | PATCH | Ensure SSH access is limited | Add deny groups"
        ansible.builtin.lineinfile:
            path: /etc/ssh/sshd_config
            regexp: '^DenyGroups|^#DenyGroups'
            line: 'DenyGroups {{ ubtu24cis_sshd.deny_groups }}'
            validate: 'sshd -t -f %s'
        notify: restart sshd
        when: "ubtu24cis_sshd['deny_groups']| default('') | length > 0"
  when:
      - ubtu24cis_rule_5_2_4
  tags:
      - level1-server
      - level1-workstation
      - rule_5_2_4
      - ssh

